// packages/react/src/WordViewer.tsx
/**
 * @word-viewer/react
 * React Word Viewer 组件
 */

import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { WordViewer } from '@word-viewer/core';
import type { ViewerOptions, DocumentSource } from '@word-viewer/core';

export interface WordViewerProps {
  source?: DocumentSource;
  options?: ViewerOptions;
  zoom?: number;
  editable?: boolean;
  theme?: 'light' | 'dark' | 'auto';
  onLoaded?: (data: any) => void;
  onError?: (error: any) => void;
  onChanged?: () => void;
  onZoom?: (level: number) => void;
  onPageChange?: (pageInfo: any) => void;
  className?: string;
  style?: React.CSSProperties;
}

export interface WordViewerRef {
  getViewer: () => WordViewer | null;
  loadDocument: (source: DocumentSource) => Promise<void>;
}

const WordViewerComponent = forwardRef<WordViewerRef, WordViewerProps>(
  (props, ref) => {
    const {
      source,
      options,
      zoom,
      editable,
      theme,
      onLoaded,
      onError,
      onChanged,
      onZoom,
      onPageChange,
      className,
      style,
    } = props;

    const containerRef = useRef<HTMLDivElement>(null);
    const viewerRef = useRef<WordViewer | null>(null);

    useEffect(() => {
      if (containerRef.current && !viewerRef.current) {
        viewerRef.current = new WordViewer(containerRef.current, {
          ...options,
          editable,
          theme,
          initialZoom: zoom,
        });

        if (onLoaded) viewerRef.current.on('loaded', onLoaded);
        if (onError) viewerRef.current.on('error', onError);
        if (onChanged) viewerRef.current.on('changed', onChanged);
        if (onZoom) viewerRef.current.on('zoom', onZoom);
        if (onPageChange) viewerRef.current.on('page-change', onPageChange);
      }

      return () => {
        if (viewerRef.current) {
          viewerRef.current.destroy();
          viewerRef.current = null;
        }
      };
    }, []);

    useEffect(() => {
      if (source && viewerRef.current) {
        loadDocument(source);
      }
    }, [source]);

    useEffect(() => {
      if (zoom !== undefined && viewerRef.current) {
        viewerRef.current.setZoom(zoom);
      }
    }, [zoom]);

    useEffect(() => {
      if (viewerRef.current) {
        editable ? viewerRef.current.enableEdit() : viewerRef.current.disableEdit();
      }
    }, [editable]);

    useEffect(() => {
      if (theme && viewerRef.current) {
        viewerRef.current.updateOptions({ theme });
      }
    }, [theme]);

    const loadDocument = async (documentSource: DocumentSource) => {
      if (!viewerRef.current) return;

      try {
        if (documentSource instanceof File) {
          await viewerRef.current.loadFile(documentSource);
        } else if (documentSource instanceof Blob) {
          const buffer = await documentSource.arrayBuffer();
          await viewerRef.current.loadBuffer(buffer);
        } else if (documentSource instanceof ArrayBuffer) {
          await viewerRef.current.loadBuffer(documentSource);
        } else if (typeof documentSource === 'string') {
          await viewerRef.current.loadUrl(documentSource);
        }
      } catch (error) {
        console.error('加载文档失败:', error);
      }
    };

    useImperativeHandle(ref, () => ({
      getViewer: () => viewerRef.current,
      loadDocument,
    }));

    return (
      <div
        ref={containerRef}
        className={`react-word-viewer ${className || ''}`}
        style={{
          width: '100%',
          height: '100%',
          minHeight: '400px',
          ...style,
        }}
      />
    );
  }
);

WordViewerComponent.displayName = 'WordViewer';

export default WordViewerComponent;

// packages/vue/src/WordViewer.vue
<template>
  <div ref="containerRef" class="vue-word-viewer"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { WordViewer } from '@word-viewer/core';

type ViewerOptions = any;
type DocumentSource = any;

interface Props {
  source?: DocumentSource;
  options?: ViewerOptions;
  zoom?: number;
  editable?: boolean;
  theme?: 'light' | 'dark' | 'auto';
}

const props = defineProps<Props>();
const emit = defineEmits<{
  loaded: [data: any];
  error: [error: any];
  changed: [];
  zoom: [level: number];
  'page-change': [pageInfo: any];
}>();

const containerRef = ref<HTMLElement | null>(null);
let viewer: WordViewer | null = null;

onMounted(() => {
  if (containerRef.value) {
    viewer = new WordViewer(containerRef.value, {
      ...props.options,
      editable: props.editable,
      theme: props.theme,
      initialZoom: props.zoom,
    });

    viewer.on('loaded', (data) => emit('loaded', data));
    viewer.on('error', (error) => emit('error', error));
    viewer.on('changed', () => emit('changed'));
    viewer.on('zoom', (level) => emit('zoom', level));
    viewer.on('page-change', (pageInfo) => emit('page-change', pageInfo));

    if (props.source) {
      loadDocument(props.source);
    }
  }
});

onBeforeUnmount(() => {
  if (viewer) {
    viewer.destroy();
    viewer = null;
  }
});

watch(() => props.source, (newSource) => {
  if (newSource) loadDocument(newSource);
});

watch(() => props.zoom, (newZoom) => {
  if (viewer && newZoom !== undefined) {
    viewer.setZoom(newZoom);
  }
});

watch(() => props.editable, (newEditable) => {
  if (viewer) {
    newEditable ? viewer.enableEdit() : viewer.disableEdit();
  }
});

watch(() => props.theme, (newTheme) => {
  if (viewer && newTheme) {
    viewer.updateOptions({ theme: newTheme });
  }
});

async function loadDocument(source: DocumentSource) {
  if (!viewer) return;
  try {
    if (source instanceof File) {
      await viewer.loadFile(source);
    } else if (source instanceof Blob) {
      const buffer = await source.arrayBuffer();
      await viewer.loadBuffer(buffer);
    } else if (source instanceof ArrayBuffer) {
      await viewer.loadBuffer(source);
    } else if (typeof source === 'string') {
      await viewer.loadUrl(source);
    }
  } catch (error) {
    console.error('加载文档失败:', error);
  }
}

function getViewer(): WordViewer | null {
  return viewer;
}

defineExpose({ getViewer, loadDocument });
</script>

<style scoped>
.vue-word-viewer {
  width: 100%;
  height: 100%;
  min-height: 400px;
}
</style>
