// packages/lit/src/word-viewer.ts
/**
 * @word-viewer/lit
 * Lit Web Component for Word Viewer
 */

import { LitElement, html, css } from 'lit';
import { customElement, property, query } from 'lit/decorators.js';
import { WordViewer } from '@word-viewer/core';
import type { ViewerOptions, DocumentSource } from '@word-viewer/core';

@customElement('word-viewer')
export class WordViewerElement extends LitElement {
  static styles = css`
    :host {
      display: block;
      width: 100%;
      height: 100%;
      min-height: 400px;
    }

    .container {
      width: 100%;
      height: 100%;
    }
  `;

  @property({ type: String })
  src?: string;

  @property({ type: Number })
  zoom: number = 1.0;

  @property({ type: Boolean })
  editable: boolean = false;

  @property({ type: String })
  theme: 'light' | 'dark' | 'auto' = 'light';

  @property({ type: Boolean })
  readonly: boolean = false;

  @query('.container')
  private container!: HTMLDivElement;

  private viewer: WordViewer | null = null;
  private _source: DocumentSource | null = null;

  set source(value: DocumentSource | null) {
    this._source = value;
    if (this.viewer && value) {
      this.loadDocument(value);
    }
  }

  get source(): DocumentSource | null {
    return this._source;
  }

  firstUpdated() {
    this.initViewer();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this.viewer) {
      this.viewer.destroy();
      this.viewer = null;
    }
  }

  private initViewer() {
    if (!this.container) return;

    const options: ViewerOptions = {
      editable: this.editable,
      theme: this.theme,
      initialZoom: this.zoom,
      readOnly: this.readonly,
    };

    this.viewer = new WordViewer(this.container, options);

    this.viewer.on('loaded', (data) => {
      this.dispatchEvent(
        new CustomEvent('loaded', { detail: data, bubbles: true, composed: true })
      );
    });

    this.viewer.on('error', (error) => {
      this.dispatchEvent(
        new CustomEvent('error', { detail: error, bubbles: true, composed: true })
      );
    });

    this.viewer.on('changed', () => {
      this.dispatchEvent(
        new CustomEvent('changed', { bubbles: true, composed: true })
      );
    });

    this.viewer.on('zoom', (level) => {
      this.dispatchEvent(
        new CustomEvent('zoom', { detail: level, bubbles: true, composed: true })
      );
    });

    this.viewer.on('page-change', (pageInfo) => {
      this.dispatchEvent(
        new CustomEvent('page-change', {
          detail: pageInfo,
          bubbles: true,
          composed: true,
        })
      );
    });

    if (this.src) {
      this.viewer.loadUrl(this.src);
    } else if (this._source) {
      this.loadDocument(this._source);
    }
  }

  async loadDocument(source: DocumentSource) {
    if (!this.viewer) return;

    try {
      if (source instanceof File) {
        await this.viewer.loadFile(source);
      } else if (source instanceof Blob) {
        const buffer = await source.arrayBuffer();
        await this.viewer.loadBuffer(buffer);
      } else if (source instanceof ArrayBuffer) {
        await this.viewer.loadBuffer(source);
      } else if (typeof source === 'string') {
        await this.viewer.loadUrl(source);
      }
    } catch (error) {
      console.error('加载文档失败:', error);
    }
  }

  getViewer(): WordViewer | null {
    return this.viewer;
  }

  setZoom(level: number) {
    if (this.viewer) {
      this.viewer.setZoom(level);
      this.zoom = level;
    }
  }

  enableEdit() {
    if (this.viewer) {
      this.viewer.enableEdit();
      this.editable = true;
    }
  }

  disableEdit() {
    if (this.viewer) {
      this.viewer.disableEdit();
      this.editable = false;
    }
  }

  async exportToPDF(): Promise<Blob | null> {
    if (this.viewer) {
      return await this.viewer.exportToPDF();
    }
    return null;
  }

  exportToHTML(): string | null {
    if (this.viewer) {
      return this.viewer.exportToHTML();
    }
    return null;
  }

  updated(changedProperties: Map<string, any>) {
    super.updated(changedProperties);

    if (!this.viewer) return;

    if (changedProperties.has('src') && this.src) {
      this.viewer.loadUrl(this.src);
    }

    if (changedProperties.has('zoom')) {
      this.viewer.setZoom(this.zoom);
    }

    if (changedProperties.has('editable')) {
      this.editable ? this.viewer.enableEdit() : this.viewer.disableEdit();
    }

    if (changedProperties.has('theme')) {
      this.viewer.updateOptions({ theme: this.theme });
    }
  }

  render() {
    return html`<div class="container"></div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'word-viewer': WordViewerElement;
  }
}

// packages/vue/src/WordViewer.vue
<template>
  <div ref="containerRef" class="vue-word-viewer"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { WordViewer } from '@word-viewer/core';

type ViewerOptions = any;
type DocumentSource = any;

interface Props {
  source?: DocumentSource;
  options?: ViewerOptions;
  zoom?: number;
  editable?: boolean;
  theme?: 'light' | 'dark' | 'auto';
}

const props = defineProps<Props>();
const emit = defineEmits<{
  loaded: [data: any];
  error: [error: any];
  changed: [];
  zoom: [level: number];
  'page-change': [pageInfo: any];
}>();

const containerRef = ref<HTMLElement | null>(null);
let viewer: WordViewer | null = null;

onMounted(() => {
  if (containerRef.value) {
    viewer = new WordViewer(containerRef.value, {
      ...props.options,
      editable: props.editable,
      theme: props.theme,
      initialZoom: props.zoom,
    });

    viewer.on('loaded', (data) => emit('loaded', data));
    viewer.on('error', (error) => emit('error', error));
    viewer.on('changed', () => emit('changed'));
    viewer.on('zoom', (level) => emit('zoom', level));
    viewer.on('page-change', (pageInfo) => emit('page-change', pageInfo));

    if (props.source) {
      loadDocument(props.source);
    }
  }
});

onBeforeUnmount(() => {
  if (viewer) {
    viewer.destroy();
    viewer = null;
  }
});

watch(() => props.source, (newSource) => {
  if (newSource) loadDocument(newSource);
});

watch(() => props.zoom, (newZoom) => {
  if (viewer && newZoom !== undefined) {
    viewer.setZoom(newZoom);
  }
});

watch(() => props.editable, (newEditable) => {
  if (viewer) {
    newEditable ? viewer.enableEdit() : viewer.disableEdit();
  }
});

watch(() => props.theme, (newTheme) => {
  if (viewer && newTheme) {
    viewer.updateOptions({ theme: newTheme });
  }
});

async function loadDocument(source: DocumentSource) {
  if (!viewer) return;
  try {
    if (source instanceof File) {
      await viewer.loadFile(source);
    } else if (source instanceof Blob) {
      const buffer = await source.arrayBuffer();
      await viewer.loadBuffer(buffer);
    } else if (source instanceof ArrayBuffer) {
      await viewer.loadBuffer(source);
    } else if (typeof source === 'string') {
      await viewer.loadUrl(source);
    }
  } catch (error) {
    console.error('加载文档失败:', error);
  }
}

function getViewer(): WordViewer | null {
  return viewer;
}

defineExpose({ getViewer, loadDocument });
</script>

<style scoped>
.vue-word-viewer {
  width: 100%;
  height: 100%;
  min-height: 400px;
}
</style>
